### ISSUE TITLE
use what format to save the AUs value got by openface to pkl file ?

### ISSUE THREAD

**Issue by IvyGongoogle** [donydchen/ganimation_replicate#13]
Hello, I use [openface](https://github.com/TadasBaltrusaitis/OpenFace) 
`/xxx/OpenFace/build/bin/FaceLandmarkImg -f  zzz.jpg -aus`
and get the out in output csv file:
```
face, confidence, AU01_r, AU02_r, AU04_r, AU05_r, AU06_r, AU07_r, AU09_r, AU10_r, AU12_r, AU14_r, AU15_r, AU17_r, AU20_r, AU23_r, AU25_r, AU26_r, AU45_r, AU01_c, AU02_c, AU04_c, AU05_c, AU06_c, AU07_c, AU09_c, AU10_c, AU12_c, AU14_c, AU15_c, AU17_c, AU20_c, AU23_c, AU25_c, AU26_c, AU28_c, AU45_c
0, 0.975, 0.91, 0.00, 0.41, 0.00, 0.00, 0.43, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.27, 0.00, 0.00, 0.00, 0.00, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0
```
 but can you show some codes about use what format to pickle the AUs value to aus_openface.pkl ? dict?

Anyone can give some advises? @donydchen

**Comment by donydchen** [comment]
Hi @IvyGongoogle , sorry for the late reply. 
As mentioned in [README](https://github.com/donydchen/ganimation_replicate#use-own-datasets), only AU intensity is used in this project, presented in the openface output file with a '_r' postfix.  
For the pickle file, python dictionary is stored inside, which should be `{img_id: [AU intensity]}`. Refer to how this item is called in the project for more details, kindly  check https://github.com/donydchen/ganimation_replicate/blob/a2ca194ec422aa2145404ce414dfc218c3a42f5c/data/base_dataset.py#L39 and https://github.com/donydchen/ganimation_replicate/blob/a2ca194ec422aa2145404ce414dfc218c3a42f5c/data/celeba.py#L15

Hope it clear.

**Comment by IvyGongoogle** [comment]
@donydchen  Thanks for your reply.  For `{img_id: [AU intensity]}`, it seems that `[AU intensity]` must be numpy array, and it does not work for list type.
