### ISSUE TITLE
Different Action Unit Distribution

### ISSUE THREAD

**Issue by lyumingzhi** [donydchen/ganimation_replicate#26]
I find the action unit extracted from the given celebA dataset with OpenFace  v2.0.4 as suggested in [issue](https://github.com/donydchen/ganimation_replicate/issues/5) is still different from the original action units given in the dataset.

The first one of the following two examples are generated with the provided action units, and the second one is generated with the extracted action unit with OpenFace v2.0.4. It is obviously not the same. May I know before processing images with OpenFace, is there any other processing step needed to be done?
![image](https://user-images.githubusercontent.com/43129252/174958429-49eaaac2-3941-48ce-82b1-6b6451955b8d.png)

![image](https://user-images.githubusercontent.com/43129252/174960722-1709e032-eab3-4410-8a05-79f927e0b57d.png)

**Comment by donydchen** [comment]
Hi @lyumingzhi, as far as I can recall, before using OpenFace, I use `face_recognition` to locate and extract the face region from the given image, similar to what I have mentioned in this [comment](https://github.com/donydchen/ganimation_replicate/issues/5#issuecomment-493028582).

Perhaps the better way would be to re-train the model by yourself, in that case you can freely choose your own pre-processing manner. Hope it help.

**Comment by lyumingzhi** [comment]
Wow, thank you very much for your instant reply! I discover that I wrongly matched the image and action units. Now, as I update the image, they are almost the same. I also check the action Unit value and find the extracted ones are very closed to the given ones, though there is subtly different.
