### ISSUE TITLE
Downloading images

### ISSUE THREAD

**Issue by basic0908** [donydchen/ganimation_replicate#27]
Hey I am not a computer science major(Psychology) but I would like to use your model for my research. 
Please help me out with this error.
I am getting a RuntimeError that the size of a tensor (2832) must match the size of tensor b(2835).
Can anyone help me how to fix this?
Thank you in advance!

![image](https://user-images.githubusercontent.com/100826336/226257587-4e69d78c-39fe-4beb-b152-5bec6c8a8c06.png)

**Comment by heberteguedes** [comment]
Up
