### ISSUE TITLE
Can you share the model in other ways? I can't open the google disk.

### ISSUE THREAD

**Issue by c1a1o1** [donydchen/ganimation_replicate#3]
Can you share the model in other ways? I can't open the google disk.
great work！
Thank you very much！

**Comment by donydchen** [comment]
Hi @c1a1o1 , thanks for your interest and suggestion. I have uploaded a copy to the BaiduPan(百度网盘), kindly refer to the README for the download link.

**Comment by c1a1o1** [comment]
Thank you very much！
