### ISSUE TITLE
Questions about Data Clearning

### ISSUE THREAD

**Issue by RegisWu** [donydchen/ganimation_replicate#8]
Thanks for sharing the nice work!

I also tried to re-implement GANimation in the past. However, when I downloaded and looked into the EmotioNet dataset, I found a lot of useless facial images such as cartoon and icons.

Could you briefly share your idea about clean out the EmotioNet dataset? It would be very helpful for me.

Looking forward to hearing from you!
Thanks!

**Comment by donydchen** [comment]
@RegisWu Apologies for the very late reply.

I employed the python package `face_recognition` to extract human face and then used `Openface` to extract Action Units vectors. So those images that can meet the above two requirements, retained, while those cannot detect any face nor AU vector, removed.

Hope it help.

**Comment by RegisWu** [comment]
Noted with thanks!
